# Generated by Django 5.1 on 2024-08-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
    ]
