# Generated by Django 5.1 on 2024-08-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_remove_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='github_id',
            new_name='facebook_id',
        ),
    ]
