# Generated by Django 5.1 on 2024-09-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanHotel', '0009_alter_branch_manager'),
        ('userauths', '0004_rename_github_id_userprofile_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='OceanHotel.branch'),
        ),
    ]
