# Generated by Django 5.1 on 2024-09-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanHotel', '0010_coupon_alter_booking_payment_status_feedback_invoice_and_more'),
        ('userauths', '0005_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='OceanHotel.branch'),
        ),
    ]
