# Generated by Django 5.0.7 on 2024-07-31 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanHotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendees',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventattendees',
            name='attendee',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='statusCheckin',
            new_name='deposit_paid',
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='CheckinReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('checkin_date', models.DateTimeField()),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_receipts', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OceanHotel.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventAttendees',
        ),
    ]
