# Generated by Django 5.0.7 on 2024-08-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OceanHotel', '0002_alter_branch_status_roomtype_room_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='success_id',
        ),
    ]
