# Generated by Django 5.0.7 on 2024-07-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanHotel', '0002_remove_eventattendees_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='LyDo',
            new_name='reason',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(through='OceanHotel.ReservationService', to='OceanHotel.service'),
        ),
    ]
