# Generated by Django 5.0.7 on 2024-08-06 07:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OceanHotel', '0004_remove_booking_num_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
