# Generated by Django 5.1 on 2024-08-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OceanHotel', '0005_roomtype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='full_name',
        ),
    ]
