# Generated by Django 5.1 on 2024-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanHotel', '0007_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmationCode',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
