# Generated by Django 5.1 on 2024-10-04 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OceanHotel', '0011_booking_invoice_alter_invoice_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_invoice', to='OceanHotel.invoice'),
        ),
    ]
